### ISSUE TITLE
Allow different mask implementations in Carousels

### ISSUE THREAD

**Issue by jmcmaster956** [bbc/tal#407]
All carousels currently extend from the carouselcore class. This class imports and sets the mask on the carousel from within the constructor, which means that is not currently possible to use a different mask implementation.

What would be very useful is to set a different mask to be used, that would allow us to extend the base mask class with some extended functionality and use this instead.

Have you any thoughts on the best way to do this within the framework? I can raise a pull request for this work

**Comment by tsadler1988** [comment]
Hi,

Apologies for the delay in responding.

Using a different mask sounds entirely sensible - we actually override `Mask.prototype` to change the functionality, which is not ideal!

We would suggest adding an optional 3rd parameter in the Carousel Core constructor, named something like `CustomMask` or `MaskConstructor`, so you can pass in a custom mask constructor for it to use rather than the default.

Tom

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).

Clsing this issue as seems to be answeed by @tsadler1988
