### ISSUE TITLE
There is no way to disable the fade-in effect when new component (page) is displayed.

### ISSUE THREAD

**Issue by h3xxx** [bbc/tal#432]
From the documentation I know that I can disable animations at all for a device.
I don't want to disable all animations, but just a transition effect when changing application's pages (based on component).

I have tried adding:
```
"defaults": {
    "showElementFade": {
        "fps": 25,
        "duration": 0,
        "easing": "linear"
    },
    "hideElementFade ": {
        "fps": 25,
        "duration": 0,
        "easing": "linear"
    }
  },
```
to <device__name>.json config file, it disabled fadein anim but there was a short gap before displaying new page (component)

Is there any other way to disable transition effect when new page is displayed?

**Comment by dhurrell** [comment]
Hi Roger,

I assume you're showing a new component using ComponentContainer. There is a cleaner way to disable the fade animation via config, found buried here:
https://github.com/bbc/tal/blob/6.4.0/static/script/widgets/componentcontainer.js#L134

However, I would expect your approach to have the same result. If you still have trouble, the delay may be caused by the fact that ComponentContainer loads the RequireJS modules for new components asynchronously, so there will be a server roundtrip the first time a component is displayed in a session. You can work around this by adding the component's module to the Require array elsewhere in the app (e.g. in the main application file), which will ensure that the module is loaded on startup.

Hope this helps - let us know how you get on.

**Comment by h3xxx** [comment]
Hi David,

This ```config.widgets.componentcontainer.fade``` way is working very similar to my way but the gap looks shorter. I think it's acceptable right now. Yes, there is no gap when modules are loaded before by RequireJS.

Thank you for help, David
