### ISSUE TITLE
Paginated Carousels.

### ISSUE THREAD

**Issue by jaikumartj** [bbc/tal#464]
How to pause scrolling in the carousel untill the focus reaches the end of the screen?

**Comment by subsidel** [comment]
This can be achieved by having lists inside the carousel, so that the list acts like a page.
For example, if this needs to happen along the x axis and you want 2 pages of content, where 3 buttons fills the width of the screen - you will need a widget structure similar to:
```
Carousel(Horizontal) [
  HorizontalList[ button1, button2, button3 ], HorizontalList[ button4, button5, button6 ]
]
```
This will result in a scrolling only occurring when going between button3 and button4. 
You will need to set the alignment options on the carousel to be correct for the size of the screen ie `3 x button.width`
