### ISSUE TITLE
Carousel - Navigator and aligner for last few items.

### ISSUE THREAD

**Issue by premjoy7** [bbc/tal#473]
Hello TAL team,

We would like to get your inputs to tweak navigator and aligner. In carousel sample, we see last item gets aligned towards extreme left as we navigate to end of carousel, leaving empty space on the right side. Can this be avoided? As we reach end of carousel, we would like to have focus moving without alignment similar to: http://i.imgur.com/Pka6ZY1.gif

Carousel configuration goes as below:

                    orientation: Carousel.orientations.HORIZONTAL,
                    carouselId: 'verticalCullingCarousel',
                    animOptions: {
                        skipAnim: false
                    },
                    alignment: {
                        normalisedAlignPoint: 0.0,
                        normalisedWidgetAlignPoint: 0.0
                    },
                    initialItem: 0,
                    type: "CULLING",

Looking forward your inputs. Thank you.

**Comment by subsidel** [comment]
In order to achieve this effect you will need to either tweak the width of the mask in CSS, or change the carousel's align points.
If you don't want to change the on screen size of the mask, try setting `normalisedAlignPoint: 0.1`

See the **Aligning** section in the carousel documentation for more explanation as to how the align points work. https://bbc.github.io/tal/widgets/carousel.html
