### ISSUE TITLE
How to compile the project ?

### ISSUE THREAD

**Issue by ghost** [bbc/tal#507]
I have an example project running on nodejs server (https://github.com/bbc/talexample), how to compile it into index.html, css and js to test in WebOS simulator?

**Comment by Arunprasanth** [comment]
@aicreate , You can run it locally using node index.js . Then right click on the page and get the source of the page save it into an html file. Then copy the tal folder from node_modules and paste it in the same folder. The same way you can copy the static folder also from your solution . Then try to run the html file 
Note : Just have a look into the html file and make sure all the js files included by the script tag are added in the solution folder

**Comment by aicreate** [comment]
@Arunprasanth hm, I thought there is a way with command line tools like in enyo project

>     enyo pack --production -d ./build --no-inline-css --css-outfile app.css --no-inline-js --js-outfile app.js

are you sure that you use the right way ?

**Comment by lionralfs** [comment]
There is no need to compile anything actually. Just follow the [instructions](https://github.com/bbc/talexample#getting-started) from the example and the app should just run. Before trying to run it on a simulator, you could also verify that the application is working by testing it in a browser. If your node server is running on port `1337` (like in the example), just go to `http://localhost:1337` in your browser.
You can basically look at the `views/index.mustache` file as being your `index.html`.

@Arunprasanth you might run into some issues by doing that. Since the index.html is automatically generated by the node server (using the mustache templates in the `views` directory) you might be missing some device-specific features that get dynamically applied during the rendering of the mustache template. For example: UWP apps need some additional JavaScript to make sure the app doesn't scale (take a look at the [`tal-page-strategies`](https://github.com/bbc/tal-page-strategies) repository).

**Comment by lionralfs** [comment]
> We are basically using UWP app so the direct node based hosting wont work out here. 

Why not? As far as I know, you can use an URL instead of an html file.
From [here](https://blogs.windows.com/buildingapps/2016/09/30/uwp-hosted-web-app-on-xbox-one-app-dev-on-xbox-series/):

Open the appxmanifestfile. 
* Under the Application tab, find the Start page text field.
* Replace html with your website URL.

<hr>

> Also if we want to host the tal application in TFS then also we need a html file.

I'm not very experienced with TFS, but I found a [sample app](https://docs.microsoft.com/en-us/vsts/pipelines/archive/apps/nodejs/nodejs-to-azure?view=tfs-2017) which uses nodejs to build an http server. I'm guessing you could use a combination of this sample app and the tal-example app to make tal work on TFS.

**Comment by Arunprasanth** [comment]
@lionralfs  Hi , I got your point and thanks for the information. But the method you are mentioned only work with hosted UWP appls, Is there any way to convert tal application as a native UWP app rather than a hosted one ?For native app we need html files I guess.

**Comment by Crasheng** [comment]
Hello, I am working with the framework now, and i also try to check the app on WebOS LG as i can see the index.html has on-fly dynamically generated content using node server, how could i wrap the app or package it for LG?

Could Anyone helps with that?

 Thanks

**Comment by kukulaka** [comment]
We have deprecated this project and there are no plans for active development going forward.

Please see the [deprecation notice](https://github.com/bbc/tal#deprecation-announcement-12122022).

Apologies for not keeping the community up to date - we are looking to engage more in future.
