### ISSUE TITLE
deployment Clarification

### ISSUE THREAD

**Issue by crasheng91** [bbc/tal#532]
Hi.

Firstly this framework is a great piece of work.
Thanks to everyone worded on it,

In my company we came to agree using TAL because it supports a lot of devices and OSs .
So the question is asking for help a clear guide how we could test the TAL app on a real tv.

is there a specific packager for each platform.
Samsung provide Cloud App Tv which we could serve our application online and provide Samsung Store the link and icon.

For LG for an example it need s (.ipk) file.. which is something need us to package the the sample app to . run on TV..

Is there a clear doc how to deploy the sample app and the development i am doing on a real TV..

You help will be much appreciated

**Comment by Crasheng** [comment]
There's no support?

**Comment by tsadler1988** [comment]
Hi @crasheng91, @Crasheng,

This type of question has been asked in a few different ways (#465, #367, #290, #281); unfortunately this is not something we can provide support for due to the number of manufacturers we support, and as different devices can have differing instructions for different models/years of device. We would advise that developers use the manufacturer's official documentation.

Tom
